services:
  traefik:
    # リバースプロキシ用イメージ：https://hub.docker.com/_/traefik
    image: traefik:3.5.3

    # 自動再起動設定
    restart: "always"

    # 外部に公開するポートの設定
    ports:
      - 22:22
      - 80:80
      - 443:443
      # - 8000:8000

    # おまじない
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro    # Dockerソケット
      - ./traefik.yml:/etc/traefik/traefik.yml:ro       # traefik設定ファイル

  # traefik用ラベル設定
    labels:
      # 明示的に公開する設定
      traefik.enable: true
      # リバースプロキシとつながるネットワーク名を書く
      traefik.docker.network: shared
      # dashboardサービスを指定
      traefik.http.routers.dashboard.service: api@internal
      # エントリポイントからのアクセスをルーティングする
      traefik.http.routers.dashboard.entrypoints: web
      # ドメインからのアクセスをルーティングする
      traefik.http.routers.dashboard.rule: Host(`traefik.example.com`)
      # traefik.http.routers.dashboard.rule: Host(`localhost`)
      # 以下はHTTPSの設定をする場合
      # traefik.http.routers.dashboard.entrypoints: secure
      # traefik.http.routers.dashboard.tls: true
      # traefik.http.routers.dashboard.tls.certresolver: default

    # 自サービス内部用・他サービスとの通信用の両方のネットワークに所属させる
    networks:
      - default
      - shared

# リバースプロキシとサービスを接続するsharedネットワークを使用
networks:
  shared:
    external: true
