services:
  # GitLab 本体
  gitlab:
    image: gitlab/gitlab-ce:18.11.2-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 22

    # SSH ポートのみホストに公開し、Web は Traefik 経由で公開
    ports:
      - "2222:22"
    expose:
      - "80"

    volumes:
      # GitLab の設定、ログ、データをホストのディレクトリにマッピング
      - ./config:/etc/gitlab

      # GitLab のログとデータをホストのディレクトリにマッピング
      - ./logs:/var/log/gitlab

      # GitLab のデータをホストのディレクトリにマッピング
      - ./data:/var/opt/gitlab

    # ヘルスチェック設定
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 1m        # チェック間隔
      timeout: 10s        # タイムアウト
      retries: 5          # リトライ回数
      start_period: 3m    # 初回起動の猶予時間（長めに設定）

    shm_size: "256m"

    # Dashboard 公開（compose ラベル管理）
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      # SSH over TCP
      - traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.gitlab-ssh.entrypoints=ssh
      - traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh

      # HTTP dashboard
      - traefik.http.routers.gitlab-http.rule=Host(`gitlab.example.com`)
      - traefik.http.routers.gitlab-http.entrypoints=web
      - traefik.http.routers.gitlab-http.service=gitlab-web
      # - traefik.http.routers.gitlab-http.middlewares=redirect-to-https

      # HTTPS dashboard
      - traefik.http.routers.gitlab-https.rule=Host(`gitlab.example.com`)
      - traefik.http.routers.gitlab-https.entrypoints=websecure
      - traefik.http.routers.gitlab-https.tls=true
      - traefik.http.routers.gitlab-https.service=gitlab-web

      # backend port
      - traefik.tcp.services.gitlab-ssh.loadbalancer.server.port=22
      - traefik.http.services.gitlab-web.loadbalancer.server.port=80

      # Middleware
      # - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

    # network は Traefik と GitLab 関連の両方に接続
    networks:
      - proxy
      - gitlab-network

  # GitLab Runner
  gitlab-runner:
    image: gitlab/gitlab-runner:v18.11.2
    container_name: gitlab-runner
    restart: unless-stopped
    depends_on:
        - gitlab

    volumes:
      # GitLab Runner の設定をホストのディレクトリにマッピング
      - './config-runner:/etc/gitlab-runner'
      # GitLab Runner が Docker コマンドを実行できるようにするため、Docker ソケットをマッピング
      - '/var/run/docker.sock:/var/run/docker.sock'

    # GitLab Runner は GitLab と同じネットワークにだけ接続
    networks:
      - gitlab-network

networks:
  proxy:
    name: proxy
    external: true
  gitlab-network:
    driver: bridge
